name: Test compilation

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  check_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
      - name: make Checking
        run: cd output && make
        timeout-minutes: 2